<template>
  <div>
    <v-dialog
      v-model="showModal"
      width="500"
      :persistent="true"
    >
      <v-card class="rounded-lg">
        <v-card-title class="text-left white--text primary pb-4">
          <span class="text-h3">
            Confirm Purchase
          </span>
          <v-icon
            size="20"
            color="white"
            @click="closeDailog"
          >
            mdi-close
          </v-icon>
        </v-card-title>
        <v-card-text>
          <v-select
            v-model="planLength"
            :items="planLengthItems"
            label="Length of installment plan"
            @change="planLengthChange"
          />
          <v-select
            v-model="downPayment"
            :items="downPaymentItems"
            label="Down Payment"
            @change="downPaymentChange"
          />
          <v-card class="pa-4">
            <div class="d-flex justify-space-between align-center mb-2">
              <span class="text-h3">Transaction Details</span>

              <v-icon
                @click="show = !show"
              >
                {{ show ? 'mdi-chevron-up' : 'mdi-chevron-down' }}
              </v-icon>
            </div>
            <v-expand-transition>
              <div
                v-show="show"
              >
                <v-divider />
                <div
                  class="mt-2"
                  style="font-size: 14px"
                >
                  <div class="d-flex justify-space-between">
                    <span class="d-flex align-center">
                      <span class="mr-1">Original Purchase Price</span>
                      <tooltips tip-text="The Original Purchase Price refers to the initial price of the NFT without the use of any financial instruments." />
                    </span>
                    <span>100USDT</span>
                  </div>
                  <div class="d-flex justify-space-between">
                    <span class="d-flex align-center">
                      <span class="mr-1">Interest Fee</span>
                      <tooltips tip-text="Interest Fee is the amount of interest generated by using leverage and other financial instruments, which depends on the Original Purchase Price, the chosen leverage ratio and duration." />
                    </span>
                    <span>
                      100USDT
                      <span class="grey--text">({{ interestRate }}%)</span>
                    </span>
                  </div>
                  <div class="d-flex justify-space-between">
                    <span class="d-flex align-center">
                      <span class="mr-1">Down Payment Amount</span>
                      <tooltips tip-text="The Down Payment Amount is the initial price that needs to be paid, which is equal to the Original Purchase Price when no financial instruments are used." />
                    </span>
                    <span>
                      100USDT
                      <span class="grey--text">(10%)</span>
                    </span>
                  </div>
                  <div class="d-flex justify-space-between">
                    <span class="d-flex align-center">
                      <span class="mr-1">Monthly Payments</span>
                      <tooltips tip-text="Monthly Payments are the fees that need to be paid on a monthly basis when using financial instruments, which can be paid partially or entirely using the revenue generated by the NFT." />
                    </span>
                    <span>
                      100USDT
                      <span class="grey--text">(10%)</span>
                    </span>
                  </div>
                  <div class="d-flex justify-space-between">
                    <span class="d-flex align-center">
                      <span class="mr-1">Length of installment plan</span>
                      <tooltips tip-text="Length of Plan refers to the duration of the plan that can be selected when using financial instruments, during which the buyer can enjoy the right to revenue generated by the NFT." />
                    </span>
                    <span>{{ planLengthEnum[planLength] }}</span>
                  </div>
                  <div class="d-flex justify-space-between">
                    <span class="d-flex align-center">
                      <span class="mr-1">Total Purchase Amount</span>
                      <tooltips tip-text="Total Purchase Amount is the total cost required to purchase the NFT, which includes the Down Payment Amount and Interest Fee." />
                    </span>
                    <span>100USDT</span>
                  </div>
                </div>
              </div>
            </v-expand-transition>
          </v-card>
          <v-card class="pa-4 my-4">
            <div class="d-flex justify-space-between align-center mb-2">
              <span class="text-h3">Transaction Details Explain</span>

              <v-icon
                @click="showExplain = !showExplain"
              >
                {{ showExplain ? 'mdi-chevron-up' : 'mdi-chevron-down' }}
              </v-icon>
            </div>
            <v-expand-transition>
              <div
                v-show="showExplain"
              >
                <v-divider />
                <div
                  class="mt-2"
                  style="font-size: 14px"
                >
                  Unlock the potential of ARKS-NFTs with just one down payment. Enjoy exclusive rights to NFT earnings, offset or eliminate interest costs, and watch your investment thrive. Act now for financial freedom with ARKS-NFT.
                </div>
              </div>
            </v-expand-transition>
          </v-card>
          <v-btn
            width="100%"
            color="primary"
            rounded
          >
            BUY
          </v-btn>
        </v-card-text>
      </v-card>
    </v-dialog>
  </div>
</template>

<script>
  import Web3 from 'web3'
  import ARKSMain from '@/abi/ARKSMain.json'
  import ARKSTestUSDT from '@/abi/ARKSTestUSDT.json'
  import { mainAddress, testUSDTAddress } from '@/abi/contractdata'
  import Tooltips from '@/components/Tooltips'
  import BigNumber from 'bignumber.js'

  export default {
    name: 'PurchaseModal',
    components: { Tooltips },
    props: {
      showModal: {
        type: Boolean,
        default: false,
      },
      cardDetail: {
        type: Object,
        default: null,
      },
      type: {
        type: Number,
        default: 1,
      },
      amount: {
        type: Number,
        default: 1,
      },
    },
    data () {
      return {
        fromAddress: null,
        show: true,
        showExplain: true,
        planLength: 3,
        planLengthEnum: {
          0: 'None',
          3: '3 month',
          5: '5 month',
          8: '8 month',
        },
        planLengthItems: [
          { text: 'Make full payment at once', value: 0 },
          { text: '3 month', value: 3 },
          { text: '5 month', value: 5 },
          { text: '8 month', value: 8 },
        ],
        downPayment: null,
        downPaymentItems: [],
        interestRate: 0,
      }
    },
    async mounted () {
      if (window.ethereum) {
        const web3 = new Web3(window.web3.currentProvider)
        this.fromAddress = await web3.eth.getAccounts()
        this.mainContract = new web3.eth.Contract(
          ARKSMain,
          mainAddress,
        )
        this.testContract = new web3.eth.Contract(
          ARKSTestUSDT,
          testUSDTAddress,
        )
        this.getBuyPlanDownPayment()
      }
    },
    methods: {
      closeDailog () {
        this.$emit('close-purchase-modal')
      },
      getBuyPlanDownPayment () {
        this.mainContract.methods.getBuyPlanDownPayment(this.fromAddress[0], this.type, this.amount, this.planLength).call().then(res => {
          console.log(res, 'getBuyPlanDownPayment')
          const firstnumber = new BigNumber(res)
          this.downPaymentItems = [
            { text: `${firstnumber}%`, value: res },
            { text: `${firstnumber.plus(10)}%`, value: res + 10 },
            { text: `${firstnumber.plus(20)}%`, value: res + 20 },
          ]
        })
      },
      getBuyPlanInterestRate () {
        this.mainContract.methods.getBuyPlanInterestRate(this.fromAddress[0], this.type, this.amount, this.downPayment, this.planLength).call().then(res => {
          console.log(res, 'getBuyPlanInterestRate')
          this.interestRate = new BigNumber(res).dividedBy(100).toFormat()
          console.log(this.interestRate, 'getBuyPlanInterestRate')
        })
      },
      planLengthChange (val) {
        if (val === 0) {
          this.downPaymentItems = [
            { text: '100%', value: 1 },
          ]
        } else {
          this.getBuyPlanDownPayment()
        }
        this.downPayment = null
      },
      downPaymentChange (val) {
        this.getBuyPlanInterestRate()
      },
    },
  }
</script>
<style lang="scss" scoped>
.text-field-wrap {
  display: flex;
  align-items: center;
}
</style>
